import * as THREE from 'three';

/**
 * Houdini VEX + Python Mathematical Bridge for Three.js
 * 
 * Replicates the geometry-level operations executed by Houdini VEX shaders
 * (disaster_deform.vfl & recovery_highlight.vfl) and the Python controller.
 */

export interface DisasterRegionConfig {
  bboxMin: [number, number, number];
  bboxMax: [number, number, number];
  displacementScale: number;
  noiseFrequency: number;
}

export const DEFAULT_DISASTER_REGION: DisasterRegionConfig = {
  bboxMin: [-7.0, 0.0, 5.0],
  bboxMax: [3.0, 9.5, 9.0],
  displacementScale: 0.35,
  noiseFrequency: 0.85,
};

// Procedural 3D noise approximation of VEX anoise()
function vexSimplexNoise(x: number, y: number, z: number): [number, number, number] {
  const s = Math.sin(x * 1.5 + y * 2.1 + z * 0.9);
  const c = Math.cos(x * 2.3 - y * 1.1 + z * 1.7);
  const m = Math.sin(x * 0.7 + y * 1.3 - z * 2.5);
  return [s * 0.5, c * 0.5, m * 0.5];
}

/**
 * Applies Houdini VEX point deformation to a geometry mesh.
 */
export function applyHoudiniVexDeformation(
  geometry: THREE.BufferGeometry,
  config: DisasterRegionConfig = DEFAULT_DISASTER_REGION,
  blend: number = 1.0 // 1.0 = full disaster, 0.0 = full recovery
) {
  const positionAttr = geometry.getAttribute('position');
  if (!positionAttr) return;

  // Cache or retrieve original pristine positions (v@orig_P)
  if (!geometry.userData.originalPositions) {
    const orig = new Float32Array(positionAttr.array.length);
    orig.set(positionAttr.array);
    geometry.userData.originalPositions = orig;
  }

  const origP = geometry.userData.originalPositions as Float32Array;
  const currentP = positionAttr.array as Float32Array;

  const [minX, minY, minZ] = config.bboxMin;
  const [maxX, maxY, maxZ] = config.bboxMax;

  for (let i = 0; i < positionAttr.count; i++) {
    const idx = i * 3;
    const ox = origP[idx];
    const oy = origP[idx + 1];
    const oz = origP[idx + 2];

    // Bounding box test
    if (ox >= minX && ox <= maxX && oy >= minY && oy <= maxY && oz >= minZ && oz <= maxZ) {
      if (blend <= 0.001) {
        // Recovery: return to original position
        currentP[idx] = ox;
        currentP[idx + 1] = oy;
        currentP[idx + 2] = oz;
      } else {
        const [nx, ny, nz] = vexSimplexNoise(
          ox * config.noiseFrequency,
          oy * config.noiseFrequency,
          oz * config.noiseFrequency
        );

        // Controlled VEX displacement
        const dispX = nx * config.displacementScale * blend;
        const dispY = -Math.abs(ny) * (config.displacementScale * 0.4) * blend;
        const dispZ = nz * config.displacementScale * blend;

        currentP[idx] = ox + dispX;
        currentP[idx + 1] = oy + dispY;
        currentP[idx + 2] = oz + dispZ;
      }
    } else {
      // Outside affected region: remains pristine
      currentP[idx] = ox;
      currentP[idx + 1] = oy;
      currentP[idx + 2] = oz;
    }
  }

  positionAttr.needsUpdate = true;
  geometry.computeVertexNormals();
}

/**
 * Creates controlled debris geometry as generated by the Houdini Python process.
 */
export function createControlledDebrisGroup(): THREE.Group {
  const debrisGroup = new THREE.Group();
  debrisGroup.name = 'houdini_disaster_debris';

  const debrisMat = new THREE.MeshStandardMaterial({
    color: 0x94a3b8,
    roughness: 0.85,
    metalness: 0.1,
  });

  // Clustered debris chunks placed along the base apron of bays 1-3
  const debrisLocations: [number, number, number, number, number, number][] = [
    [-4.5, 0.2, 7.8, 0.45, 0.25, 0.35],
    [-3.8, 0.18, 8.2, 0.35, 0.3, 0.4],
    [-2.2, 0.22, 7.9, 0.5, 0.22, 0.3],
    [-1.5, 0.15, 8.4, 0.38, 0.18, 0.32],
    [0.2, 0.2, 8.0, 0.42, 0.26, 0.38],
    [1.1, 0.16, 7.7, 0.3, 0.2, 0.28],
    [-3.0, 0.12, 8.6, 0.25, 0.15, 0.25],
    [-0.8, 0.14, 8.3, 0.32, 0.18, 0.26],
  ];

  debrisLocations.forEach(([x, y, z, sx, sy, sz], idx) => {
    const geo = new THREE.DodecahedronGeometry(sx * 0.8, 0);
    const mesh = new THREE.Mesh(geo, debrisMat);
    mesh.position.set(x, y, z);
    mesh.scale.set(1, sy / sx, sz / sx);
    mesh.rotation.set(idx * 0.4, idx * 0.7, idx * 0.2);
    mesh.castShadow = true;
    debrisGroup.add(mesh);
  });

  return debrisGroup;
}
